#! /bin/sh
xrdb ~/.Xresources ;
sxhkd -c $HOME/.config/sxhkd/sxhkdrc  $HOME/.config/sxhkd/appconfig &
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config top_padding          10
# Set the border colors.
bspc config normal_border_color "#1C1E26"
bspc config active_border_color "#1C1E26"
bspc config focused_border_color "#1C1E26"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#E95678"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "#E95678"

bspc config border_width         0
bspc config window_gap           13
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config ignore_ewmh_focus  	 true
bspc config focus_follows_pointer true
bspc config click_to_focus button1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:MusicPlayer sticky=on state=floating
bspc rule -a URxvt:scratchy sticky=on state=floating
bspc rule -a firefox:Toolkit sticky=on state=floating
WM_CLASS: "surf" "Surf"
WM_CLASS: "firefox" "Firefox"
bspc rule -a Surf state=tiled
WM_CLASS: "emacs " "Emacs"
bspc rule -a Emacs desktop='^1'
bspc rule -a Emacs state=tiled
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^5' follow=off
bspc rule -a MusicPlayer sticky=on state=floating
bspc rule -a scratchy sticky=on state=floating
$HOME/.config/bspwm/autostart;
