#! /bin/sh
sxhkd &
bspc monitor -d 1 2 3 4 5 
bspc config top_padding          13
. "${HOME}/googledark.sh"

# Set the border colors.
bspc config normal_border_color "$(xrdb  -query | grep 'color0'| awk '{print $NF}')"
bspc config active_border_color "$(xrdb  -query | grep 'color10'| awk '{print $NF}')"
bspc config focused_border_color "$(xrdb  -query | grep 'color4'| awk '{print $NF}')"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$(xrdb  -query | grep 'color4'| awk '{print $NF}')"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "$(xrdb  -query | grep 'color2'| awk '{print $NF}')"

bspc config border_width         2
bspc config window_gap           13
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true 
bspc config click_to_focus button1
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
ignore_ewmh_fullscreen = true
WM_CLASS: "surf" "Surf"
bspc rule -a Surf state=tiled
bWM_CLASS: "emacs " "Emacs"
bspc rule -a Emacs desktop='^1'
bspc rule -a Emacs state=tiled
bspc rule -a Discord desktop='^5'
bspc rule -a discord desktop='^5'

# reloaddunst so it work better
reload_dunst;
$HOME/.config/polybar/launch.sh;
